export const SymbolsType = {
  DIGITO: 'sdigito',
  PROGRAMA: 'sprograma',
  SE: 'sse',
  ENTAO: 'sentao',
  SENAO: 'ssenao',
  ENQUANTO: 'senquanto',
  FACA: 'sfaca',
  INICIO: 'sinicio',
  FIM: 'sfim',
  ESCREVA: 'sescreva',
  LEIA: 'sleia',
  VAR: 'svar',
  INTEIRO: 'sinteiro',
  BOOLEANO: 'sbooleano',
  VERDADEIRO: 'sverdadeiro',
  FALSO: 'sfalso',
  PROCEDIMENTO: 'sprocedimento',
  FUNCAO: 'sfuncao',
  DIV: 'sdiv',
  E: 'se',
  OU: 'sou',
  NAO: 'snao',
  IDENTIFICADOR: 'sidentificador',
  DOISPONTOS: 'sdoispontos',
  ATRIBUICAO: 'satribuicao',
  MAIS: 'smais',
  MENOS: 'smenos',
  MULTI: 'smulti',
  MAIORIGUAL: 'smaiorigual',
  MAIOR: 'smaior',
  MENORIGUAL: 'smenorigual',
  MENOR: 'smenor',
  DIFERENTE: 'sdiferente',
  IGUAL: 'sigual',
  PONTOVIRGULA: 'spontoVirgula',
  VIRGULA: 'svirgula',
  ABREPARENTESES: 'sabreParenteses',
  FECHAPARENTESES: 'sfechaParenteses',
  PONTO: 'sponto',
};

export const ErrorType = {
  MISSING_CLOSE_BRACE: 'Faltando o caractere }',
  MISSING_CLOSE_COMMENT: 'Faltando */',
  MISSING_STAR: 'Faltando *',
  INVALID_CARACTERE: 'Caractere inválido',
  MISSING_PROGRAM: 'Está faltando a palavra reservada programa.',
  MISSING_IDENTIFIER: 'Está faltando um identificador',
};
