export const SymbolsType = {
  DIGITO: 'sdigito',
  PROGRAMA: 'sprograma',
  SE: 'sse',
  ENTAO: 'sentao',
  SENAO: 'ssenao',
  ENQUANTO: 'senquanto',
  FACA: 'sfaca',
  INICIO: 'sinicio',
  FIM: 'sfim',
  ESCREVA: 'sescreva',
  LEIA: 'sleia',
  VAR: 'svar',
  INTEIRO: 'sinteiro',
  BOOLEANO: 'sbooleano',
  VERDADEIRO: 'sverdadeiro',
  FALSO: 'sfalso',
  PROCEDIMENTO: 'sprocedimento',
  FUNCAO: 'sfuncao',
  DIV: 'sdiv',
  E: 'se',
  OU: 'sou',
  NAO: 'snao',
  IDENTIFICADOR: 'sidentificador',
  DOISPONTOS: 'sdoispontos',
  ATRIBUICAO: 'satribuicao',
  MAIS: 'smais',
  MENOS: 'smenos',
  MULTI: 'smulti',
  MAIORIGUAL: 'smaiorigual',
  MAIOR: 'smaior',
  MENORIGUAL: 'smenorigual',
  MENOR: 'smenor',
  DIFERENTE: 'sdiferente',
  IGUAL: 'sigual',
  PONTOVIRGULA: 'spontoVirgula',
  VIRGULA: 'svirgula',
  ABREPARENTESES: 'sabreParenteses',
  FECHAPARENTESES: 'sfechaParenteses',
  PONTO: 'sponto',
};

export const SymbolTableType = {
  PROGRAM: 'nomedeprograma',
  VARIABLE: 'variavel',
  PROCEDURE: 'procedimento',
  FUNCTION_INTEGER: 'funcao_inteira',
  FUNCTION_BOOLEAN: 'funcao_booleana',
};

export const PrecedenceTableType = {
  INTEGER: 'inteiro',
  BOOLEAN: 'booleano',
  BOTH: 'ambos',
};

export const ErrorType = {
  MISSING_CLOSE_BRACE: 'Faltando o caractere }',
  MISSING_CLOSE_COMMENT: 'Faltando */',
  MISSING_STAR: 'Faltando *',
  INVALID_CARACTERE: 'Caractere inválido',
  MISSING_PROGRAM: 'Está faltando a palavra reservada programa.',
  MISSING_IDENTIFIER: 'Está faltando um identificador',
  MISSING_POINT_COMMA: 'Está faltando um ponto e vírgula',
  MISSING_COMMA: 'Está faltando uma vírgula',
  MISSING_PONT: 'Está faltando ponto',
  MISSING_FINAL_ERROR_COMMENT_EOF: 'Não é final de arquivo ou não comentário',
  MISSING_VAR: 'Está faltando palavra reservada var',
  MISSING_OPEN_PARENTHESES: 'Está faltando abrir o parenteses',
  MISSING_CLOSE_PARENTHESES: 'Está faltando fechar o parenteses',
  MISSING_DOUBLE_POINT: 'Está faltando dois pontos',
  MISSING_INIT: 'Está faltando a palavra reservada inicio',
  MISSING_THEN: 'Está faltando a palavra reservada entao',
  MISSING_DO: 'Está faltando a palavra reservada faca',
  INVALID_TYPE: 'Tipo de variável indefinido',
  INVALID_FACTOR: 'Fator inválido',
  INVALID_COMMA: 'Virgula inválida',
  INVALID_OPERATION:
    "Operação inválida! Esperando atribuição ':=' ou chamada de procedimento ';'",
  DUPLICATED: 'Identificador duplicado',
  UNDECLARED: 'Identificador não declarado',
  UNDECLARED_VAR: 'Variável não declarada',
  UNDECLARED_FUNC: 'Função não declarada',
  UNDECLARED_PROC: 'Procedimento não declarado',
};
